### ISSUE TITLE
Config: support all resources on classpath

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1214]
Current implementation of config sources for classpath resources only uses the first resource found.
We should support (both from meta-config and from a builder) adding config source for each instance of a resource on a classpath.
Usage:
`microprofile-config.properties` already requires this approach. We can do this using a builder through `ConfigSources.classpathAll("META-INF/microprofile-config.properties")`, we must be able to do the same thing through `meta-config`

Example `meta-config` (an option how to implement):
```
sources:
  - type: "multi"
     source-type: "classpath"
     properties:
       resource: "microprofile-config.properties"
```

The `multi` would tell meta configuration that this would return multiple instances of a config source.
The `source-type` would point to a named ConfigSourceProvider.
This would probably require additional method in `ConfigSourceProvider`:
`List<ConfigSource> createMulti(String type, Config metaConfig)`
