### ISSUE TITLE
Web server security configuration in Helidon MP

### ISSUE THREAD

**Issue by mattjlewis** [oracle/helidon#1267]
##  Environment Details
* Helidon Version: 2.0-SNAPSHOT
* Helidon MP
* JDK version: 11.0.5
* OS: MacOS 10.15.2
* Docker version (if applicable): N/A

----------

## Problem Description
Following examples and documentation I was unable to get the embedded web server security to work in my Helidon MP application. It seems that you have to set the web-server config at the root and include an empty security.web-server element. All of the configuration in the security.web-server seems to be ignored and only the settings in the root web-server config is processed. The root web-server configuration is not processed unless there is an empty security.web-server element.

## Steps to reproduce
Example application.yaml file:
```
security:
  providers:
    - http-basic-auth:
        realm: "HelidonTxTest"
        users:
          - login: "admin1"
            password: "${CLEAR=password}"
            roles: ["user", "admin"]
          - login: "user1"
            password: "${CLEAR=password}"
            roles: ["user"]
  web-server:

web-server:
  defaults:
    authenticator: "http-basic-auth"
    audit: true
    authenticate: true
    authorize: true
    authentication-optional: false
    roles-allowed: ["user"]
  paths:
    - path: "/{*}"
      methods: ["get"]
      authenticate: true
      authorize: true
      authentication-optional: false
      roles-allowed: ["user"]
```
