### ISSUE TITLE
Add support for property reference to meta configuration

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1312]
When configuring Config using "Meta configuration" file, we can define locations of configuration files, though we cannot use a reference to a system property or environment variable.

Especially for examples, it would be great if we could reference the user home directory. Some of the examples require secrets to be defined (such as application id and secret for OIDC and IDCS connections), in such cases, our examples use references, so an override can be used to configure the actual secrets.
We should have the possibility to configure such a "default" override from user's home directory without coding it in `Main` class.

The example `examples/microprofile/idcs` requires such a configuration. It would be great if I could create the following `meta-config.yaml`:
```yaml
sources:
  - type: "system-properties"
  - type: "environment-variables"
  - type: "file"
    properties:
      optional: true
      path: "${user.home}/helidon/conf/examples.yaml"
  - type: "classpath"
    properties:
      optional: true
      resource: "application.yaml"
  - type: "classpath"
    properties:
      optional: true
      resource: "META-INF/microprofile-config.properties"
```

Where the `${user.home}` could be either as is (and use the system properties and environment variables as sources for value), or even `${SYS.user.home}` or `${ENV.user.home}` to explicitly define the source of the property value.
Easiest option would be to combine the `meta-config.yaml` with system properties and environment variables and resolve it as a config reference.
