### ISSUE TITLE
Change the way Resource builder is loaded from Config

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1331]
Currently the `Resource` uses the following approach to configuration
```yaml
trust:
  keystore-path: "file base"
  # keystore-classpath-location: "classpath"
  type: "PKCS12"
```

This is a prefix based approach that is hard to understand and use.

For 2.0, we should change it to:
```yaml
trust:
  location:
    path: "file base"
    #classpath: "classpath"
  type: "PKCS12"
```

This way the `Resource` class would use the `location` key to find the content of the resource,
 and the user is free to add any configuration keys on the level of `trust` in the example above.
In current version, these additional keys (such as `type`) are on the same level and may cause conflicts or loss of clarity.
