### ISSUE TITLE
Documentation request. How to secure content with StaticContentSupport

### ISSUE THREAD

**Issue by oobles** [oracle/helidon#1654]
This should be a really easy one, but I can't seem to find a solution. How do you secure content registered with StaticContentSupport? I'd like to have /protected static content and open static content, with Routing looking something like this:

return Routing.builder()
.register(WebSecurity.create(getSecurity()))
.register("/protected", StaticContentSupport.builder(protectedPath).welcomeFileName("index.html").build())
.register("/", StaticContentSupport.builder(openPath).welcomeFileName("index.html").build())
.error(Exception.class, (req, res, ex) -> {
    res.status(Http.Status.NOT_FOUND_404).send();
})
.build();

What else is required to secure /protected?

**Comment by oobles** [comment]
After a lot of trial and error, we worked out the following:

return Routing.builder()
.register(WebSecurity.create(getSecurity()))
.get("/protected[/{**}][/{*}]", WebSecurity.authenticate())
.register("/", StaticContentSupport.builder(openPath).welcomeFileName("index.html").build())
.error(Exception.class, (req, res, ex) -> {
res.status(Http.Status.NOT_FOUND_404).send();
})
.build();

It would be good to add this type of sample to your documentation. ie Sample of catch all Path matcher (nothing there currently) and security on static content.

**Comment by spericas** [comment]
Perhaps this could be a _guide_ about static content support and how to handle this use case.

**Comment by ljamen** [comment]
@m0mus , 
Can you please add this to the doc epic 1515 so we can track it?

**Comment by m0mus** [comment]
@ljamen done

**Comment by tomas-langer** [comment]
Quick reference - you can configure all of this in configuration file (both in Helidon SE and Helidon MP):

```yaml
security:
  providers:
    - abac: # <1>
    - provider-key: # <2>
  web-server:
    defaults:
      authenticate: true # <3>
    paths:
      - path: "/metrics[/{*}]" # <4>
        roles-allowed: "admin"
      - path: "/health[/{*}]" # <5>
        roles-allowed: "monitor" 
      - path: "/openapi[/{*}]" # <6>
        abac:
          scopes: ["openapi"]
      - path: "/static[/{*}]" # <7>
        roles-allowed: ["user", "monitor"]
```

<1> Attribute based access control provider that checks roles and scopes
<2> The provider(s) used in your application, such as `oidc`
<3> Default configuration for all configured paths
<4> Protection of `/metrics` and all nested paths with `admin` role required
<5> Protection of `/health` and all nested paths with `monitor` role required
<6> Protection of `/openapi` and all nested paths with `openapi` scope required
<7> Protection of static content configured on `/static` path with either `user` or `monitor` role required

In Helidon SE, you would use `WebSecurity.create(config)`.
In Helidon MP, you just need to have this configuration used by Helidon (e.g. using `application.yaml`

I will verify this configuration now and update if I missed anything. I will also create a PR with documentation update.
