### ISSUE TITLE
Consider additional format for CORS config

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#1662]
The CORS support allows configuration to override CORS SE and MP settings in code or on annotations (in MP). 

The implementation currently handles this format:
```
cors:
  paths:
    - path-prefix: /cors1
      allow-origins: ["*"]
      allow-methods: ["*"]
    - path-prefix: /cors2
      allow-origins: ["http://foo.bar", "http://bar.foo"]
      allow-methods: ["DELETE", "PUT"]
      allow-headers: ["X-bar", "X-foo"]
      allow-credentials: true
      max-age: -1
```
for controlling the endpoints in the app matching the given path prefixes. The use of path expressions allows users to control multiple endpoints with a single entry. 

Elsewhere in MP (e.g., fault tolerance) a different format looks more like this: (this example is from a recent comment by Tomas on the CORS PR):
```
io.helidon.microprofile.cors.CrossOriginTest.CorsResource2.options.value=http://foo.bar,http://bar.foo
io.helidon.microprofile.cors.CrossOriginTest.CorsResource2.options.allowHeaders=X-foo,X-bar
io.helidon.microprofile.cors.CrossOriginTest.CorsResource2.options.allowMethods=DELETE,PUT
io.helidon.microprofile.cors.CrossOriginTest.CorsResource2.options.allowCredentials=true
io.helidon.microprofile.cors.CrossOriginTest.CorsResource2.options.maxAge=-1
```

Also this issue is open on MicroProfile OpenAPI for CORS support https://github.com/eclipse/microprofile-open-api/issues/416 although from very recent comments it looks as if it will be rejected, leaving it to implementations. 

Once we release 2.0 we should remember to comment on that issue because Quarkus is mentioned as having it and the comment talks about double-checking on Thorntail and WildFly.

This issue is for triggering some thought and discussion about supporting the alternative format as well.
