### ISSUE TITLE
Meta configuration in MP

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1737]
## Environment Details
* Helidon Version: master branch 2.0
* Helidon MP
----------

MP Config specification does not describe how to handle meta configuration. Config should load all config sources available on classpath.

This means that for each config file/classpath resource, you need to have a config source that supports it.
Considering the capability to override configuration properties, it would be great to configure something similar to this:
```yaml
add-discovered-sources: true
add-discovered-converters: true
add-default-sources: true
sources:
 - type: "yaml"
    path: "/conf/application.yaml"
    optional: true
 - type: "yaml"
    classpath: "application.yaml"
    optional: true
 - type: "properties"
    path: "/conf/prod.properties"
``` 

We currently support this through Helidon SE Config meta configuration, which uses SE Config sources - this works fine, but does not support the expected mutability of MP Config.
