### ISSUE TITLE
DbClient - tracing works from config, not from code

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1777]
2.0.0-M3

When tracing is added using code:
```java
.addInterceptor(DbClientTracing.create())
```
it is ignored and trace is not generated. When added in config:
```yaml
db:
  source: jdbc
  connection:
    url: "jdbc:h2:tcp://localhost:9092/test"
  interceptors:
    tracing:
      global:
```

It works as expected
