### ISSUE TITLE
Multiple security configuration

### ISSUE THREAD

**Issue by ottuzzi** [oracle/helidon#2165]
## Environment Details
* Helidon Version: 1.4.5
* Helidon MP
* JDK version: OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
* OS: Windows10
* Docker version (if applicable): N/A

----------

## Problem Description
I have a Helidon MP service that is configured to use Keycloak as OIDC but I would like to expose some rest endpoint (something like metrics or health) with a simple basic authentication: is this possible? If it is not possible what is the suggested way to handle this case?

**Comment by tomas-langer** [comment]
This is possible in the following way:
1. Configure both providers in your configuration
2. For metrics, openAPI and health - these do not use JAX-RS, so you can specify their protection using WebServer security. In the configuration, you can define an explicit provider name 
3. For JAX-RS, you can specify a provider name in Helidon annotations `Authenticated` and `Authorized`

**Comment by tomas-langer** [comment]
Example webserver configuration (under `security`):
```yaml
  web-server:
    defaults:
      authenticate: true
    paths:
       # metrics and any sub-path
      - path: "/metrics[/{*}]"
        authenticator: "http-basic-auth"
```
