### ISSUE TITLE
Security MP service not triggered for metrics

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2296]
## Environment Details
* Helidon Version: 1.4.7
* Helidon MP
* JDK version: 1.8
----------

## Problem Description

- when I configure security to protect metrics endpoint (using web server security), it may not get triggered, as security MP service has same priority as metrics MP service

Example configuration:
```yaml
security:
  providers:
    - abac:
    - http-basic-auth:
        realm: "helidon"
        users:
          - login: "success"
            password: "password"
            roles: ["admin"]
          - login: "fail"
            password: "password"
  web-server:
    paths:
      - path: "/metrics[/{*}]"
        authenticate: true
        authorize: true
        abac:
          roles-allowed:
            user:
              - admin
```

Please also validate this works as it should in 2.0
