### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2334]
Add support for gzip compression in Helidon.

This should be configurable for WebServer, e.g.:
```yaml
server:
    port: 8080
    compression:
      enabled: true
```
