### ISSUE TITLE
Add Support of Hashicorp Vault into Helidon

### ISSUE THREAD

**Issue by ak98neon** [oracle/helidon#2395]
Please add support of Hashicorp Vault https://www.vaultproject.io/ into Helidon Framework.

**Comment by tomas-langer** [comment]
Hello, could you please describe the use case - esp. what you expect from Helidon.
I can see an integration as a config source - so you could inject `@ConfigProperty` into CDI beans with configuration obtained from the Vault.

If you have ideas how this could work, we would welcome them. If not, we will choose the mode of integration as we see fit, which may not be aligned with the use case(s) you have.

Thanks a lot!

**Comment by maheshmuthulankkat** [comment]
Hi,
I have given below some of our use cases related to Vault. We currently use Spring vault.
1. Connect to vault and retrieve secrets. Interface something similar to Spring vault VaultVersionedKeyValueOperations.
2. Core vault interaction. Interface something similar to Spring vault VaultTemplate
3. Kubernetes based authentication to vault. Details at https://docs.spring.io/spring-vault/docs/current/reference/html/#vault.authentication.kubernetes

**Comment by vipinjnair** [comment]
Hi,

It would be great if a Vault Rest based client be added to the Helidon package. 

Listing out some Vault use cases that we are currently using : 

-- Authentication  : 1) Token based 
                                2) Kubernetes based

-- Reading and Writing to KeyValue secret engine

-- Reading and Writing to Transit Engine. Creating new encryption key, key rotation and version based key fetch.

The proposed Helidon based Vault client  can provide interfaces to interact with different vault secret engines and to manage authentication. 

thanks
Vipin

**Comment by rijureghunath1** [comment]
Few additional use-case, based on our experience on working with Hashicorp and OCI vault.

1. The implementation should work with different vault impl (Hashicorp, OCI etc.).

2. Support to design an application without real or minimal knowledge of Vault and its API's. For Hashcorp vault provides init / sidecar pattern for containers on Kubernetes based deployments.

3. Library support should be there to export transit key to the caller based on provided parameter's such as transit key path and name. 

4. Multiple engine support. Key engines we uses with our applications are KV, PKI and Transit

5. Good support for muti-tenant SAAS applications. For e.g each tenant could be owning different KV data storage containing data specific to that tenant An easy way for CRUD is desirable by abstracting necessary stuffs within the library.

**Comment by tomas-langer** [comment]
Todos after the draft PR:

- Add CDI module with blocking/synchronous methods equivalent to the current reactive ones (e.g. return the Response directly rather than return a Single<Response>
- Maybe add explicit support for tracing (can be enabled now through builder, by adding the tracing client service, or through configuration by enabling services + configuration)
- DTTO for metrics in SE/MP
- Validate all modules exist in bom/pom.xml
- Finish reactive examples (documentation)
- Add CDI examples
- Add documentation
- Validate native image (all examples)
- Update AOT documentation (SE and MP for the new modules)
- Update FeatureCatalog with the new modules
- Validate module-info.java exists for all modules (except for examples)
- Validate an example using module path with full module info for both SE and MP
- Check and document integration with Tracing
- Check and document integration with HealthChecks (maybe add a health check for OCI?)
- Check and document integration with Metrics
- Add a proper integration test using k8s that validates database secrets engine and k8s vault authentication

k8s pod definition that works (I ran local tests and examples against it):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: vault
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "pokemon"
    - name: vault
      image: vault
      ports:
        - containerPort: 8200
      env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "myroot"
```
