### ISSUE TITLE
Add possibility to override lists in config

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2455]
Consider following two sources:
`main`:
```
security.providers:
  - abac:
 - oidc:
    client-id: "abcd" 
```

`test`:
```
security.providers:
 - abac:
 - http-basic-auth:
    realm: "helidon"
```

What I want to achieve:
 I want to be able to use HTTP Basic authentication for unit tests, but Open ID Connect provider for production.

What happens:
Security fails to start, as there is more than one security provider specified on second position

Why?
Because the merging happens on property name level. And as arrays are stored as indexed properties, we end up with:
```
security.providers.0.abac=
security.providers.1.oidc.client-id=abcd
security.providers.1.http-basic-auth.realm=helidon
```

When security iterates over the providers, it identifies that on position `1` we have two keys (`oidc` and `http-basic-auth`) and fails.

What should happen:
We need to find a way to nicely override such configuration - may require a different way to configure things

**Comment by tomas-langer** [comment]
A possible solution is to update lists to use a different pattern (such as when we configure sockets for server).
In security, this would be:

```
security.providers:
  - type: "abac"
    name: "abac" # (optional, required only when more than one provider of the same type configured)
  - type: "http-basic-auth"
    realm: "helidon"
```

This would be (in properties):
```
security.providers.0.type=abac
security.providers.0.name=abac
security.providers.1.type=http-basic-auth
security.providers.1.realm=helidon
```

This way we could easily override providers in test configuration by specifying a different `type` and other configuration.
