### ISSUE TITLE
Outbound configuration for OIDC provider must be defined incorrectly

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2537]
Helidon 2.1.0

For outbound security to work correctly with OIDC provider, we must define:
```yaml
- oidc
  outbound:
    outbound:
      - name: "outbound-config"
         hosts: ["*"]
```

The `outbound` should only be defined once.
