### ISSUE TITLE
Key performance indicator (KPI) metrics and perhaps other vendor metrics not exposed on default port if other routings defined

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#3239]
## Environment Details
* Helidon Version: 2.3.1
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
A user reports that setting up additional ports causes the KPI metrics and maybe other vendor metrics to _not_ appear on the default routing.
> when we have additional ports, e.g. for health and metrics, I’m seeing that we don’t get these kpi metrics for the default http port. Is there maybe some additional configuration I’m missing?
It actually maybe looks like the kpi metrics, and some of the other vendor metrics, are only applied to the “metrics” port with this config

## Steps to reproduce

The user shared this configuration:
```
server:
  port: 8080
  host: 0.0.0.0
  sockets:
    - name: health
      port: 8081
      bind-address: 0.0.0.0
    - name: metrics
      port: 8082
      bind-address: 0.0.0.0
metrics:
  routing: "metrics"
  key-performance-indicators:
    extended: "true"
```
