### ISSUE TITLE
Microprofile Server Builder offers no flexibility in customising the Webserver programmatically

### ISSUE THREAD

**Issue by gcameo** [oracle/helidon#3727]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:  2.4.0
* Helidon SE or Helidon MP: Helidon MP
* JDK version: 17
* OS:  All
* Docker version (if applicable): N/A

----------

## Problem Description
When using helidon Mircroprofile, the builder offers no flexibility in allowing customisation of the web server for things such as providing your own SSLContext which is important for certain security requirements programatically

It is assumed implicitly that every configuration will be done by Yaml File.

The customisation cannot even be done via reflection.

**Comment by tomas-langer** [comment]
The customization is possible through a CDI extension or event listener.
You can create a bean with the following method:
```
private final void onStartup(@Observes @Initialized(ApplicationScoped.class) final Object event,
                                 final BeanManager beanManager)
```
this will be triggered during server startup. The WebServer is started with very low priority, so your listener will be executed first.
You can then do the following to update builder:
```
ServerCdiExtension server = bm.getExtension(ServerCdiExtension.class);
server.serverBuilder(); // to customize server setup
server.serverRoutingBuilder(); // for default routing
server.serverNamedRoutingBuilder(); // for named sockets
```

**Comment by tomas-langer** [comment]
This is intentionally not part of the `Server` class API, as the `Server` class exists only for partial backward compatibility with Helidon 1.x. 
You can use the `io.helidon.microprofile.cdi.Main` to start any Helidon MP application, and you should be able to use code such as provided above...

**Comment by spericas** [comment]
@tomas-langer Perhaps we need to provide more/better documentation on how to do this.

**Comment by gcameo** [comment]
@spericas Yes. The documentation will really help.

@tomas-langer Thanks for the pointers. I have been digging so much into this and was about to make my first Open source contribution.. lol.. But thanks for the pointers.

On another note, the following Configuration fails with MP even though it works with SE.

```
server:
  port: 443
  host: 0.0.0.0
  tls:
    client-auth: "REQUIRE"
    trust:
      keystore:
        passphrase: "Password123"
        trust-store: true
        resource:
          resource-path: "certificate.p12"
    private-key:
      keystore:
        passphrase: "Password123"
        resource:
          resource-path: "certificate.p12"
```

It fails with error 

```
Exception in thread "main" java.lang.RuntimeException: Private key not available
	at io.helidon.webserver.WebServerTls$Builder.lambda$buildKmf$2(WebServerTls.java:392)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
```

I will try what has been suggested. 

Thank you very much
