### ISSUE TITLE
Incorrect documentation for HttpSignProvider

### ISSUE THREAD

**Issue by janotav** [oracle/helidon#3908]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.4.2
* Helidon SE
* JDK version: 14.0.2
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
The HttpSignProvider documentation (https://helidon.io/docs/v2/#/se/security/02_providers#_http_signatures_provider) describes following configration option:
```
headers | [SIGNATURE,AUTHORIZATION] | Headers to look for inbound signatures and to store outbound signatures
```
Turns out that for outbound scenario the applicable setting is:
```
  outbound:
    - name: "<name>"
      signature:
        header: AUTHORIZATION
        ...
```
That corresponds to **outbound.*.signature.header** and not **header** as documented.
