### ISSUE TITLE
Helidon CLI - database sample does not work with MySQL due to case sensitivity

### ISSUE THREAD

**Issue by daffodilistic** [oracle/helidon#4187]
## Environment Details

> MacBook-Air-2:database-se daffodilistic$ helidon version
> build.date               2022-02-04 12:37:38 PST
> build.version            2.3.3
> build.revision           600f89b3
> project.version          1.0-SNAPSHOT
> project.helidon.version  2.5.0
> project.flavor           SE
> latest.helidon.version   2.5.0
> MacBook-Air-2:database-se daffodilistic$ javac --version
> javac 17.0.1
> MacBook-Air-2:database-se daffodilistic$ uname -a
> Darwin MacBook-Air-2.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
> MacBook-Air-2:database-se daffodilistic$ docker --version
> Docker version 20.10.13, build a224086

----------

## Problem Description
The database quickstart code generated by Helidon CLI fails to run if the MySQL JDBC connector is used. It appears to have hung with no detailed debug logs/output, even when starting `helidon dev` with the `--verbose` argument. It turns out that the generated quickstart code calls `row.column()` with uppercase column names (e.g. `ID_TYPE` in `PokemonMapperProvider.java`), which causes this issue.

## Steps to reproduce
1. Install Helidon CLI
2. Create a starter Helidon project with `helidon init`, select the `database` quickstart sample
3. Run the project with `helidon dev --verbose`. Observe that accessing http://localhost:8080/pokemon works as expected. Terminate the Helidon process with `^C`
4. Start a fresh MySQL Docker container (Docker Compose file follows):
```
version: '3.3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
```
Confirm that the MySQL container is up and running by using a MySQL client to connect to it using MySQL Workbench, `mysql` CLI client, DBeaver, etc.
5. Add the MySQL JDBC connector to `pom.xml`:
```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
</dependency>
```
6. Set the `db` prop in `application.yaml`:
```
db:
  source: jdbc
  connection:
    url: jdbc:mysql://127.0.0.1:3306/pokemon
    username: user
    password: password
    poolName: mysql
```
7. Run the project with `helidon dev --verbose` again. Observe that accessing http://localhost:8080/pokemon times out, despite the fact that Helidon has already started up with `WEB server is up! http://localhost:8080/pokemon` being the last line logged to the console.  Verify that the tables have already been created at this point in time via the MySQL client. Terminate the Helidon process
8. Change all `db.column` calls to use lowercase names, e.g. `ID_TYPE` to `id_type` in `PokemonMapper.read()`.
9. Restart Helidon via `helidon dev --verbose`, and access http://localhost:8080/pokemon. This should work as per normal.
