### ISSUE TITLE
BUG: CORS Config Path ordering is changed while processing CORS requests at times, causing CORS errors at random times.

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#4407]
We have below CORS configuration entries in one of our applications, with the expectation that /authorize calls should match to first entry, /callback should match to second entry and all other calls to match to last default entry. I did not find any documentation that confirms the order of these entries are important - but we assumed the processing is based on the order.

Is this expectation correct? If not, then ignore the below points - and educate me on the options that we could use to achieve the above mentioned behaviour.

If the expectation is right, then we are noticing a different random ordering behaviour at times with Helidon MP. On debugging more, I noticed that, Aggregator::findFirst receives all entries from the below configuration as List and at times, the order or elements in this list is different from the order mentioned in the configuration. This creates an issue, as the Aggregator.findFirst method picks the first entry from the ones that match the pattern.

```yaml
 cors:
   paths:
     - path-pattern: "/authorize[/{+}]"
       allow-origins: ["*"]
       allow-methods: ["GET"]
       allow-credentials: true
     - path-pattern: "/callback[/{+}]"
       allow-origins: ["*"]
       allow-methods: ["PUT", "POST"]
       allow-credentials: true
     - path-pattern: "{^(?!((authorize)|(callback))).*$}"
       allow-origins: ["http://backend-base-uri}", "http://frontend-base-uri}", "http://test-origin}", "null"]
       allow-methods: ["DELETE", "PATCH", "HEAD"]
       allow-credentials: true
 ```

## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 17
* OS: Windows 11
* Docker version (if applicable): NA
