### ISSUE TITLE
Docs: tracing guide has bad (old) k8s yaml

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#4757]
## Environment Details
* Helidon Version: 3.0.1

----------

## Problem Description

The tracing guide at https://helidon.io/docs/3.0.1/#/mp/tracing has a bad (old)  tracing.yaml under the "Deploy Your Helidon Application into Kubernetes" section. This won't work with recent version of k8s. I think it needs to look something like:

```
kind: Service
apiVersion: v1
metadata:
  name: helidon-tracing 
  labels:
    app: helidon-tracing
spec:
  type: NodePort
  selector:
    app: helidon-tracing
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-tracing
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: helidon-tracing
  template:
    metadata:
      labels:
        app: helidon-tracing
        version: v1
    spec:
      containers:
        - name: helidon-tracing
          image: helidon-tracing-mp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
```
