### ISSUE TITLE
Composite provider policy issue

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#664]
When using multiple authentication providers, we get a `401` even though one of the providers returns success.

The success comes from `http-basic-auth`

Configuration:
```
jersey:
    prematching-authentication: true 
  provider-policy:
    type: "COMPOSITE"
    authentication:
    - name: "header-atn"
      flag: "SUFFICIENT"
    - name: "jwt_oauth"
      flag: "SUFFICIENT"
    - name: "http-basic-auth"
      flag: "SUFFICIENT"
    authorization:
    - name: "abac"
      flag: "REQUIRED"
```
## Environment Details
* Helidon Version: 1.0.4-SNAPSHOT
* Helidon MP

----------
