### ISSUE TITLE
MP Metrics and Health configuration fails on alternative port

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#891]
Admin port support in MP Server does not work.

The following configuration:
```
server:
  port: 8081
  host: "localhost"
  sockets:
    - admin:
        port: 9081

metrics:
  routing: "admin"

health:
  routing: "admin"
```

Fails, as the registration of routing happens before the ports are available on the server (probably)

**Comment by tomas-langer** [comment]
Problem is with configuration - the named port is not prefixed with `-`
Correct configuration:
```
server:
  port: 8081
  host: "localhost"
  sockets:
    admin:
      port: 9081
      bind-address: "localhost"

metrics:
  routing: "admin"

health:
  routing: "admin"
```
