### ISSUE TITLE
Configuration only support for securing JAX-RS applications

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#909]
Currently we need to modify sources, or require security for every single request.
It would be good to have a configuration based approach to configure security for JAX-RS applications similar to webserver configuration.
Eample yaml:

```
security:
  jax-rs:
    resources:
      - resource-class: "io.helidon.examples.quickstart.mp.GreetResource"
        resource-method: "*"
        methods: ["GET"]
        authenticate: true
        roles-allowed: ["user", "admin"]
      - resource-class: "io.helidon.examples.quickstart.mp.GreetResource"
        methods: ["PUT", "POST"]
        authenticate: true
        roles-allowed: ["admin"]
```

**Comment by tomas-langer** [comment]
As we already have support for security webserver paths using configuration, this is not a needed feature.
This can be managed through:
```
security.web-server.paths:
 - path: "/path[/{*}]"
    methods: ["GET"]
    roles-allowed: ["admin"]
```

Each provider may support additional configuration (such as required scopes)
