### ISSUE TITLE
WebServer: Inconsistent configuration for sockets

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#929]
Here is how to configure a named socket from config file currently

```yaml
server:
  port: 8080
  sockets:
    health:
        port: 9090
```

The named socket is just an object field instead of being a named array item / map.
E.g. See how security providers are configured:

```yaml
security:
  providers:
    # HTTP Basic authentication provider
    - http-basic-auth:
        realm: "helidon"
```

Therefore the socket should be configured in a way that is consistent with other J4C components:

```yaml
server:
  port: 8080
  sockets:
    - health:
        port: 9090
```

**Comment by tomas-langer** [comment]
There is a difference here - the security name `http-basic-auth` is not arbitrary - it actually maps to a specific provider through java service loader. 
With sockets, the name is an arbitrary name of the socket, so I see two options:
1) current implementation (which is inconsistent with the rest of Helidon that uses a list of objects)
2) use a `name` property:
```
server:
  port: 8080
  sockets:
    - name: "health"
       port: 9090
    - name: "admin"
       port: 9091
```
As that is nicely aligned with the idea that `server` config node node is itself a socket configuration
that has an implicit name of `@default`

**Comment by spericas** [comment]
Thinking more about hits, any such name should be to the right of the colon and in quotes. Using meta-data instead of data seems confusing. So I like (2) and don't particularly like the current use of `http-basic-auth`.

**Comment by tomas-langer** [comment]
This requires also documentation of the configurable options - we seem to lack this currently.
Btw for `http-basic-auth` and all other security providers - the name is intended for this (and only this) use - to be a key in configuration.
For WebServer the name is an arbitrary name for a port.

**Comment by tomas-langer** [comment]
Another thing to consider - using arrays (as in `- name: "health"`) has different semantics from current approach.
*Current approach*
The set of socket configurations not ordered - and probably does not need to be, unless we want to open sockets in the sequence they are configured.
It is easy to override configuration in another config file (which seems more and more important)
*Array approach*
The socket configuration would be ordered, on the other hand making it much harder to override a value, as you need to use indexed approach. 

Example of overriding current approach:
```yaml
server:
  port: 8080
  sockets:
    health:
        port: 9090
```

You can use a system property/env var: `server.sockets.health.port=9091`

Example of overriding array approach:
```yaml
server:
  port: 8080
  sockets:
    - name: "health"
       port: 9090
```

You would need to use `server.sockets.0.port=9091`

**Comment by tomas-langer** [comment]
In addition, we should add a property `enabled` that defaults to `true`, so we can disable sockets through configuration hierarchy.

**Comment by spericas** [comment]
The override using indexes is used by MP and I think more recently by our CORS configuration as well. It don't find it that hard or confusing. Option number (2) is still my preference as it clearly separates data from meta-data. Using data as labels is more confusing IMO.

**Comment by tomas-langer** [comment]
The new configuration will look as this:

```yaml
server:
    port: 8080
    sockets:
        - name: "admin"
           port: 8090
        - name: "another"
           port: 8091
          enabled: false
```
Added support for `enabled` flag
Added support for `name` property, that is now required (also name is a property of a socket, not externalized - each Helidon socket configuration is considered named)
